/**
 * @file Automatically generated by @tsed/barrels.
 */
export * from "./BaseRestController.js";
export * from "./impl/ConfigController.js";
export * from "./impl/FrontendController.js";
export * from "./impl/StatsController.js";
export * from "./impl/SubmissionController.js";
export * from "./impl/SubmissionRoundController.js";
export * from "./impl/SubmissionRoundResultController.js";
export * from "./impl/UtilsController.js";
export * from "./impl/security/PassportCtrl.js";
